<?php
/**
 * Author archive breadcrumb item locator class.
 *
 * Used to locate the breadcrumb items for author archives.
 */
class Carbon_Breadcrumb_Locator_User extends Carbon_Breadcrumb_Locator {

	/**
	 * Whether this the items of this locator should be included in the trail.
	 *
	 * @access public
	 *
	 * @return bool $is_included Whether the found items should be included.
	 */
	public function is_included() {
		return is_author();
	}

	/**
	 * Retrieve the items, found by this locator.
	 *
	 * @access public
	 *
	 * @param int $priority The priority of the located items.
	 * @param int $user_id The author user ID.
	 * @return array $items The items, found by this locator.
	 */
	public function get_items( $priority = 1000, $user_id = 0 ) {
		// get the current post ID, if not specified
		if ( ! $user_id ) {
			$user_id = get_queried_object_id();
		}
		
		// create the author breadcrumb item
		$item = Carbon_Breadcrumb_Item::factory( $this->get_type(), $priority );
		$item->set_id( $user_id );
		$item->setup();

		return array( $item );
	}

	/**
	 * Generate a set of breadcrumb items that found by this locator type and any subtype.
	 * The author archive locator has no subtypes, so this method wraps around get_items().
	 *
	 * @access public
	 *
	 * @return array $items The items, generated by this locator.
	 */
	public function generate_items() {
		if ( ! $this->is_included() ) {
			return array();
		}

		return $this->get_items();
	}

}