<?php
/**
 * Custom breadcrumb item locator class.
 * 
 * Used as proxy for custom breadcrumb items.
 */
class Carbon_Breadcrumb_Locator_Custom extends Carbon_Breadcrumb_Locator {

	/**
	 * Whether this the items of this locator should be included in the trail.
	 *
	 * @access public
	 *
	 * @return bool $is_included Whether the found items should be included.
	 */
	function is_included() {
		return true;
	}

	/**
	 * Retrieve the items, found by this locator.
	 * Since this locator is used as a proxy, no items are returned.
	 *
	 * @access public
	 *
	 * @return array $items The items, found by this locator.
	 */
	function get_items() {
		return array();
	}

	/**
	 * Generate a set of breadcrumb items that found by this locator type and any subtype.
	 * Since this locator is used as a proxy, no items are returned.
	 *
	 * @access public
	 *
	 * @return array $items The items, generated by this locator.
	 */
	function generate_items() {
		return array();
	}
	
}